name: Publish to GitHub Packages
description: Publishes a package to GitHub Packages
author: 'LightX Innovations'

inputs:
  working-directory:
    description: 'Working directory'
    required: true
    default: '.'
  token:
    description: 'A Github PAT'
    required: true
  package-read-token:
    description: 'A Github PAT with read:packages scope'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@lightx-innovations'
        token: ${{ inputs.token }}
    - name: Authenticate with GitHub Packages
      run: echo "@lightx-innovations:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}\nalways-auth=true" > ~/.npmrc
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Install dependencies
      shell: bash
      run: npm ci
      working-directory: ${{ inputs.working-directory }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.package-read-token }}
        GITHUB_TOKEN: ${{ inputs.package-read-token }}
    - name: Run tests
      shell: bash
      run: npm test
      working-directory: ${{ inputs.working-directory }}
    - name: Publish to GitHub Packages
      shell: bash
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
        NPM_CONFIG_REGISTRY: https://npm.pkg.github.com/
      working-directory: ${{ inputs.working-directory }}
