name: Publish to GitHub Packages
description: Publishes a package to GitHub Packages
author: 'LightX Innovations'

inputs:
  working-directory:
    description: 'Working directory'
    required: true
    default: '.'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@lightx-innovations'
        token: ${{ github.token }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json
    - name: Install dependencies
      shell: bash
      run: npm ci
      working-directory: ${{ inputs.working-directory }}
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
    - name: Run tests
      shell: bash
      run: npm test
      working-directory: ${{ inputs.working-directory }}
    - name: Publish to GitHub Packages
      shell: bash
      run: npm run build:lib && npm publish ./dist --access internal
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
        NPM_CONFIG_REGISTRY: https://npm.pkg.github.com/
      working-directory: ${{ inputs.working-directory }}
