name: Publish to GitHub Packages
description: Publishes a package to GitHub Packages
author: 'LightX Innovations'

inputs:
  working-directory:
    description: 'Working directory'
    required: true
    default: '.'
  token:
    description: 'A Github PAT'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      shell: bash
      run: echo "@lightx-innovations:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}\nalways-auth=true" > .npmrc && npm ci
      working-directory: ${{ inputs.working-directory }}
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
    - name: Run tests
      shell: bash
      run: npm test
      working-directory: ${{ inputs.working-directory }}
    - name: Publish to GitHub Packages
      shell: bash
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
        NPM_CONFIG_REGISTRY: https://npm.pkg.github.com/
      working-directory: ${{ inputs.working-directory }}
