name: Publish Data Filter Node.js Package

on:
  workflow_dispatch: # Manually run the workflow

jobs:
  publish-data-filter:
    name: Publish Data Filter Package
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/publish
        with:
          working-directory: data-filter
          token: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 10
