name: Redis Node.js Package

#https://docs.github.com/en/packages/quickstart

on:
  release:
    types: [created]


jobs:
  fetch-previous-release:
    runs-on: ubuntu-latest
    outputs:
      previous_release_sha: ${{ steps.set-output.outputs.previous_release_sha }}
    steps:
      - name: Get previous release
        id: get_previous_release
        run: |
          previous_release_sha=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases | jq -r '.[1].tag_name')
          echo "::set-output name=previous_release_sha::$previous_release_sha"

  build:
    if: github.event_name == 'release' && github.sha != needs.fetch-previous-release.outputs.previous_release_sha && contains(github.event_path, 'redis/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
        working-directory: redis
      - name: Run tests
        run: npm test
        working-directory: redis

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
        packages: write
        contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: npm ci
        working-directory: redis
      - name: Publish to GitHub Packages
        run: npm publish
        working-directory: redis
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
