name: Publish Config Package

on:
  workflow_dispatch: # Manually run the workflow

jobs:
  publish-config:
    name: Publish Config Package
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/publish
        with:
          working-directory: config
          token: ${{ secrets.GITHUB_TOKEN }}
          package-read-token: ${{ secrets.PACKAGES_READ_TOKEN }}
        timeout-minutes: 10
