name: Redis Node.js Package

on:
  workflow_dispatch: # Manually run the workflow

jobs:
  publish-redis:
    name: Publish Redis Package
    runs-on: ubuntu-latest
    env:
      github-working_directory: redis
    steps:
      - uses: actions/checkout@v4
      - uses: ./jobs/publish.yaml
