name: Publish Redis Node.js Package

on:
  workflow_dispatch: # Manually run the workflow

jobs:
  publish-redis:
    name: Publish Redis Package
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/publish
        with:
          working-directory: redis
        timeout-minutes: 10
