name: Publish Common Package

on:
  workflow_dispatch: # Manually run the workflow

jobs:
  publish-common:
    name: Publish Common Package
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/publish
      with:
        working-directory: common
        token: ${{ secrets.GITHUB_TOKEN }}
      timeout-minutes: 10
