name: Publish Sequelize Node.js Package

on:
  workflow_dispatch: # Manually run the workflow

jobs:
  publish-sequelize:
    name: Publish Sequelize Package
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/publish
        with:
          working-directory: sequelize
          token: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 10
