name: Publish Access Control Package

on:
  workflow_dispatch: # Manually run the workflow

jobs:
  publish-access-control:
    name: Publish Access Control Package
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/publish
        with:
          working-directory: access-control
        timeout-minutes: 10
